### FAZER CADASTRO 
POST http://localhost:8080/api/cadastro HTTP/1.1
Content-Type: application/json

{
    "username": "teste",
    "password": "teste"
}

### LOGIN
POST http://localhost:8080/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "teste",
    "password": "teste"
}

### ACESSAR ROTA PROTEGIDA
GET http://localhost:8080/api/rota-protegida HTTP/1.1
Authorization: Bearer COLOQUE AQUI SEU TOKEN

### ATUALIZAR USUARIO
PUT http://localhost:8080/api/atualizar HTTP/1.1
Content-Type: application/json
Authorization: Bearer COLOQUE AQUI SEU TOKEN

{
    "username": "user_novo",
    "password": "asdf"
}

### APAGAR USUÁRIO
DELETE http://localhost:8080/api/apagar HTTP/1.1
Authorization: Bearer COLOQUE AQUI SOU TOKEN